### ISSUE TITLE
hello compiled your ev3-master code and run it on the ev3... seems working ... but robot is not moving! how can I test motors and sensors in elixir? thx

### ISSUE THREAD

**Issue by han88** [jfcloutier/ev3#1]

**Comment by jfcloutier** [comment]
The current configuration (see https://github.com/jfcloutier/ev3/blob/master/mix.exs) is set for mock sensors and motors. You want to uncomment the line #		 env: [{:mock, false}, {:platform, :ev3}] and comment the one before.

**Comment by han88** [comment]
great.. works! thx
